/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.ifro.calama.votacaofeedback.view;

import br.edu.ifro.calama.votacaofeedback.model.Votacao;

/**
 *
 * @author floriano
 */
public final class AprovarVotacaoView extends javax.swing.JPanel {

    /**
     * Creates new form AprovarVotacaoView
     */
    public AprovarVotacaoView() {
        initComponents();
        carregarVotacoes();
    }
public void carregarVotacoes() {
    // Simula a busca no banco de dados
    java.util.List<Votacao> votacoesDeTeste = new java.util.ArrayList<>();
    votacoesDeTeste.add(new Votacao("VOTAÇÃO PARA DIREÇÃO-GERAL", "Início: 01/08/2025"));
    votacoesDeTeste.add(new Votacao("ENQUETE DO LANCHE", "Início: 02/08/2025"));
    votacoesDeTeste.add(new Votacao("FEEDBACK DA DISCIPLINA", "Início: 03/08/2025"));

    // Limpa o painel antes de adicionar novos cards
    this.removeAll();

    // Para cada votação na lista, cria um card, o preenche, e o adiciona na tela
    for (Votacao votacao : votacoesDeTeste) {
        CardView card = new CardView();
        card.setDados(votacao);
        this.add(card);
    }

    this.revalidate();
    this.repaint();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void carregarVotacoesParaAprovacao() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
