/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.ifro.calama.votacaofeedback.view;

import br.edu.ifro.calama.votacaofeedback.model.Votacao;
import br.edu.ifro.calama.votacaofeedback.repository.VotacaoRepository;
import br.edu.ifro.calama.votacaofeedback.service.VotacaoService;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author floriano
 */
public final class AprovarVotacaoView extends javax.swing.JPanel {

    /**
     * Creates new form AprovarVotacaoView
     */
    public AprovarVotacaoView() {
        initComponents();
        carregarVotacoes();
    }

public void carregarVotacoes() {
   
    VotacaoRepository votacaoRepo = new VotacaoRepository();

    try {
       
        List<Votacao> votacoesDoBanco = votacaoRepo.buscarPendentes();

        
        painelDaGrade.removeAll();

        
        for (Votacao votacao : votacoesDoBanco) {
            CardView card = new CardView();
            
            card.setDados(votacao); 
            painelDaGrade.add(card);
        }

       
        painelDaGrade.revalidate();
        painelDaGrade.repaint();

    } catch (Exception e) {
       
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao buscar votações do banco de dados.", "Erro de Conexão", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDaGrade = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        painelDaGrade.setLayout(new java.awt.GridLayout());
        add(painelDaGrade, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

public void carregarVotacoesParaAprovacao() {
   
    List<Votacao> votacoes = new ArrayList<>();
   

    
    painelDaGrade.removeAll();

    
    for (Votacao votacao : votacoes) {
        CardView card = new CardView();
        card.setDados(votacao);
        painelDaGrade.add(card); 
    }

    
    painelDaGrade.revalidate();
    painelDaGrade.repaint();
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel painelDaGrade;
    // End of variables declaration//GEN-END:variables
}
