/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.ifro.calama.votacaofeedback.view;

/**
 *
 * @author floriano
 */
public class CardView extends javax.swing.JPanel {

    /**
     * Creates new form CardView
     */
    public CardView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInstituicao = new javax.swing.JLabel();
        lblCampus = new javax.swing.JLabel();
        Local = new javax.swing.JLabel();
        lblTituloVotacao = new javax.swing.JLabel();
        dtinicio = new javax.swing.JLabel();
        returdadosdt = new javax.swing.JLabel();
        dtfim = new javax.swing.JLabel();
        returdadosdt2 = new javax.swing.JLabel();
        dtresult = new javax.swing.JLabel();
        returdadosdt3 = new javax.swing.JLabel();
        btnVerVotacao = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInstituicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/IF.png"))); // NOI18N
        add(lblInstituicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 100));

        lblCampus.setText("campus");
        add(lblCampus, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, 20));

        Local.setText("Porto Velho Calama");
        add(Local, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        lblTituloVotacao.setText("VOTAÇÃO PARA DIREÇÃO-GERAL");
        add(lblTituloVotacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        dtinicio.setText("Data inicio");
        add(dtinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        returdadosdt.setText("resultData");
        add(returdadosdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        dtfim.setText("Data fim");
        add(dtfim, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        returdadosdt2.setText("resultDataF");
        add(returdadosdt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        dtresult.setText("Data Resultado");
        add(dtresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        returdadosdt3.setText("resultDataR");
        add(returdadosdt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        btnVerVotacao.setText("Ver Votação");
        btnVerVotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerVotacaoActionPerformed(evt);
            }
        });
        add(btnVerVotacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerVotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerVotacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerVotacaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Local;
    private javax.swing.JButton btnVerVotacao;
    private javax.swing.JLabel dtfim;
    private javax.swing.JLabel dtinicio;
    private javax.swing.JLabel dtresult;
    private javax.swing.JLabel lblCampus;
    private javax.swing.JLabel lblInstituicao;
    private javax.swing.JLabel lblTituloVotacao;
    private javax.swing.JLabel returdadosdt;
    private javax.swing.JLabel returdadosdt2;
    private javax.swing.JLabel returdadosdt3;
    // End of variables declaration//GEN-END:variables
}
