/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifro.calama.votacaofeedback.view;

import br.edu.ifro.calama.votacaofeedback.model.OpcaoVoto;
import br.edu.ifro.calama.votacaofeedback.model.Usuario;
import br.edu.ifro.calama.votacaofeedback.model.Votacao;
import br.edu.ifro.calama.votacaofeedback.repository.OpcaoVotoRepository;
import br.edu.ifro.calama.votacaofeedback.repository.VotacaoRepository;
import br.edu.ifro.calama.votacaofeedback.util.ToastUtil;
import br.edu.ifro.calama.votacaofeedback.view.CriarVotacaoView;
import br.edu.ifro.calama.votacaofeedback.view.MenuPrincipalView;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.Timer;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author floriano
 */
public class CriarVotacaoOpcoesView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CriarVotacaoOpcoesView.class.getName());
    private Usuario usuarioLogado;
    private Votacao votacaoEmAndamento;
    private List<JLabel> todosOsLabelsDeOpcao;
    private List<JTextField> todosOsCamposDeOpcao;
    private int opcoesVisiveis = 2; // Começamos com 2 opções visíveis

    /**
     * autor Athos
     */
    public CriarVotacaoOpcoesView(Usuario usuario, Votacao votacao) {
        initComponents();
        
        this.usuarioLogado = usuario;
        this.votacaoEmAndamento = votacao;
        
        if (this.usuarioLogado != null) {
            // No modo Design, dê um nome de variável para o JLabel que mostra o nome
            // (ex: labelNomeUsuario) e use-o aqui.
            labelNomeUsuario.setText(this.usuarioLogado.getNome());
        }
        
        todosOsLabelsDeOpcao = Arrays.asList(TituloO1, TituloO2, TituloO3, TituloO4, TituloO5, TituloO6, TituloO7, TituloO8);
        todosOsCamposDeOpcao = Arrays.asList(txtOpcao1, txtOpcao2, txtOpcao3, txtOpcao4, txtOpcao5, txtOpcao6, txtOpcao7, txtOpcao8);
        
        for (int i = 2; i < todosOsLabelsDeOpcao.size(); i++) {
        todosOsLabelsDeOpcao.get(i).setVisible(false);
        todosOsCamposDeOpcao.get(i).setVisible(false);
    }
        
        inicializarMenuLateral();
    }
        
    public void exibirMensagem(String mensagem) {

        ToastUtil toast = new ToastUtil(this, mensagem, ToastUtil.ToastType.ERROR, ToastUtil.ToastPosition.TOP_CENTER);
        toast.display();
    }

    public void exibirMensagemDeSucesso(String mensagem) {

        ToastUtil toast = new ToastUtil(this, mensagem, ToastUtil.ToastType.SUCCESS, ToastUtil.ToastPosition.BOTTOM_RIGHT);
        toast.display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelHeader = new javax.swing.JPanel();
        painelHeaderEsquerda = new javax.swing.JPanel();
        labelIconeMenu = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();
        painelHeaderDireita = new javax.swing.JPanel();
        labelNomeUsuario = new javax.swing.JLabel();
        labelIconePerfil = new javax.swing.JLabel();
        painelSidebar = new javax.swing.JPanel();
        menutxt = new javax.swing.JLabel();
        criarVotacao = new javax.swing.JButton();
        participarVotacao = new javax.swing.JButton();
        gerenciaVotacao = new javax.swing.JButton();
        aprovarVotacao = new javax.swing.JButton();
        votoArquivado = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        PainelConteudo = new javax.swing.JPanel();
        TituloPrincipal = new javax.swing.JLabel();
        TituloP = new javax.swing.JLabel();
        txtPergunta = new javax.swing.JTextField();
        btnAdicionarOpcao = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        TituloO1 = new javax.swing.JLabel();
        TituloO2 = new javax.swing.JLabel();
        TituloO3 = new javax.swing.JLabel();
        TituloO4 = new javax.swing.JLabel();
        TituloO5 = new javax.swing.JLabel();
        TituloO6 = new javax.swing.JLabel();
        TituloO7 = new javax.swing.JLabel();
        TituloO8 = new javax.swing.JLabel();
        txtOpcao1 = new javax.swing.JTextField();
        txtOpcao2 = new javax.swing.JTextField();
        txtOpcao3 = new javax.swing.JTextField();
        txtOpcao4 = new javax.swing.JTextField();
        txtOpcao5 = new javax.swing.JTextField();
        txtOpcao6 = new javax.swing.JTextField();
        txtOpcao7 = new javax.swing.JTextField();
        txtOpcao8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelHeader.setBackground(new java.awt.Color(0, 0, 51));
        painelHeader.setPreferredSize(new java.awt.Dimension(100, 50));
        painelHeader.setLayout(new java.awt.BorderLayout());

        painelHeaderEsquerda.setOpaque(false);
        painelHeaderEsquerda.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 5));

        labelIconeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu.png"))); // NOI18N
        labelIconeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelIconeMenuMouseClicked(evt);
            }
        });
        painelHeaderEsquerda.add(labelIconeMenu);

        labelLogo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelLogo.setForeground(new java.awt.Color(255, 255, 255));
        labelLogo.setText("OCTACORE");
        labelLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLogoMouseClicked(evt);
            }
        });
        painelHeaderEsquerda.add(labelLogo);

        painelHeader.add(painelHeaderEsquerda, java.awt.BorderLayout.LINE_START);

        painelHeaderDireita.setOpaque(false);
        painelHeaderDireita.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5));

        labelNomeUsuario.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        labelNomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelNomeUsuario.setText("Nome Usuario");
        painelHeaderDireita.add(labelNomeUsuario);

        labelIconePerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        painelHeaderDireita.add(labelIconePerfil);

        painelHeader.add(painelHeaderDireita, java.awt.BorderLayout.LINE_END);

        getContentPane().add(painelHeader, java.awt.BorderLayout.PAGE_START);

        painelSidebar.setBackground(new java.awt.Color(255, 255, 255));
        painelSidebar.setPreferredSize(new java.awt.Dimension(230, 0));
        painelSidebar.setLayout(new javax.swing.BoxLayout(painelSidebar, javax.swing.BoxLayout.Y_AXIS));
        painelSidebar.add(menutxt);

        criarVotacao.setText("Criar Votação");
        criarVotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarVotacaoActionPerformed(evt);
            }
        });
        painelSidebar.add(criarVotacao);

        participarVotacao.setText("Participar de Votação ");
        participarVotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participarVotacaoActionPerformed(evt);
            }
        });
        painelSidebar.add(participarVotacao);

        gerenciaVotacao.setText("Gerenciar Votação");
        gerenciaVotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciaVotacaoActionPerformed(evt);
            }
        });
        painelSidebar.add(gerenciaVotacao);

        aprovarVotacao.setText("Aprovar Votações\n");
        aprovarVotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aprovarVotacaoActionPerformed(evt);
            }
        });
        painelSidebar.add(aprovarVotacao);

        votoArquivado.setText("Votações Arquivadas");
        painelSidebar.add(votoArquivado);
        painelSidebar.add(filler1);

        getContentPane().add(painelSidebar, java.awt.BorderLayout.LINE_START);

        TituloPrincipal.setText("CRIAR VOTAÇÃO - OPÇÕES");

        TituloP.setText("Pergunta");

        txtPergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerguntaActionPerformed(evt);
            }
        });

        btnAdicionarOpcao.setText("Adicionar Opção.");
        btnAdicionarOpcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarOpcaoActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        TituloO1.setText("Opção 1");

        TituloO2.setText("Opção 2");

        TituloO3.setText("Opção 3");

        TituloO4.setText("Opção 4");

        TituloO5.setText("Opção 5");

        TituloO6.setText("Opção 6");

        TituloO7.setText("Opção 7");

        TituloO8.setText("Opção 8");

        txtOpcao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOpcao3ActionPerformed(evt);
            }
        });

        txtOpcao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOpcao6ActionPerformed(evt);
            }
        });

        txtOpcao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOpcao7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelConteudoLayout = new javax.swing.GroupLayout(PainelConteudo);
        PainelConteudo.setLayout(PainelConteudoLayout);
        PainelConteudoLayout.setHorizontalGroup(
            PainelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConteudoLayout.createSequentialGroup()
                .addGroup(PainelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelConteudoLayout.createSequentialGroup()
                        .addGap(1106, 1106, 1106)
                        .addComponent(TituloPrincipal))
                    .addGroup(PainelConteudoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(PainelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TituloO1)
                            .addComponent(TituloP)
                            .addComponent(TituloO7)
                            .addComponent(TituloO6)
                            .addComponent(txtPergunta, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(TituloO5)
                            .addComponent(TituloO4)
                            .addComponent(TituloO3)
                            .addComponent(TituloO2)
                            .addComponent(TituloO8)
                            .addComponent(txtOpcao1)
                            .addComponent(txtOpcao2)
                            .addComponent(txtOpcao3)
                            .addComponent(txtOpcao8)
                            .addComponent(txtOpcao7)
                            .addComponent(txtOpcao6)
                            .addComponent(txtOpcao5)
                            .addComponent(txtOpcao4))
                        .addGroup(PainelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelConteudoLayout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(btnVoltar)
                                .addGap(36, 36, 36)
                                .addComponent(btnFinalizar))
                            .addGroup(PainelConteudoLayout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(btnAdicionarOpcao)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        PainelConteudoLayout.setVerticalGroup(
            PainelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConteudoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(TituloPrincipal)
                .addGap(18, 18, 18)
                .addComponent(TituloP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TituloO1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOpcao1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TituloO2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOpcao2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TituloO3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOpcao3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TituloO4)
                .addGroup(PainelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelConteudoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOpcao4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TituloO5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOpcao5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TituloO6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOpcao6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TituloO7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOpcao7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TituloO8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOpcao8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelConteudoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnAdicionarOpcao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVoltar)
                            .addComponent(btnFinalizar))))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        getContentPane().add(PainelConteudo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelIconeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIconeMenuMouseClicked
        
        new Thread(new Runnable() {
            @Override
            public void run() {
               
                if (painelSidebar.getWidth() > 0) {
                    try {
                        
                        for (int i = painelSidebar.getWidth(); i >= 0; i--) {
                            painelSidebar.setSize(i, painelSidebar.getHeight());
                            Thread.sleep(1);
                        }
                    } catch (InterruptedException ex) {
                        System.out.println(ex);
                    }
                } else {
                    try {
                        // Animação para abrir, de 0 até a largura desejada (210)
                        for (int i = 0; i <= 210; i++) {
                            painelSidebar.setSize(i, painelSidebar.getHeight());
                            Thread.sleep(1);
                        }
                    } catch (InterruptedException ex) {
                        System.out.println(ex);
                    }
                }
            }
        }).start();
    }//GEN-LAST:event_labelIconeMenuMouseClicked

    private void labelLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLogoMouseClicked
        MenuPrincipalView telaDeCriacao = new MenuPrincipalView(this.usuarioLogado);

        telaDeCriacao.setLocationRelativeTo(null);
        telaDeCriacao.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_labelLogoMouseClicked

    private void criarVotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarVotacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criarVotacaoActionPerformed

    private void participarVotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participarVotacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_participarVotacaoActionPerformed

    private void gerenciaVotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciaVotacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gerenciaVotacaoActionPerformed

    private void aprovarVotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aprovarVotacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aprovarVotacaoActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        try {
            // 1. Coletar os dados desta segunda tela (usando os nomes do seu Navigator)
            String pergunta = txtPergunta.getText();

            // Validação simples
            if (pergunta.trim().isEmpty()) {
                exibirMensagem("O campo 'Pergunta' é obrigatório para finalizar.");
                return;
            }

            // 2. Completar o objeto 'votacaoEmAndamento' que já temos
            this.votacaoEmAndamento.setPergunta(pergunta);
            this.votacaoEmAndamento.setStatus("PENDENTE"); // Definimos o status final

            VotacaoRepository votacaoRepository = new VotacaoRepository();
            // AQUI NÓS CAPTURAMOS O ID QUE O MÉTODO RETORNA
            int idNovaVotacao = 0;
            try {
                idNovaVotacao = votacaoRepository.criar(this.votacaoEmAndamento);
            } catch (Exception ex) {
                System.getLogger(CriarVotacaoOpcoesView.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }

            // --- PARTE 2: Salvar as Opções ---
            // Apenas prossiga se a votação principal foi salva com sucesso (ID > 0)
            if (idNovaVotacao > 0) {

                OpcaoVotoRepository opcaoRepository = new OpcaoVotoRepository();

                // Salva a Opção 1, se ela tiver texto
                for (JTextField campoOpcao : todosOsCamposDeOpcao) {
                    // SÓ SALVA SE O CAMPO ESTIVER VISÍVEL E COM TEXTO
                    if (campoOpcao.isVisible() && !campoOpcao.getText().trim().isEmpty()) {
                        OpcaoVoto opcao = new OpcaoVoto();
                        opcao.setDescricao(campoOpcao.getText().trim());
                        opcao.setIdVotacao(idNovaVotacao);
                        opcaoRepository.criar(opcao);
                    }
                }

                exibirMensagemDeSucesso("Votação criada com sucesso!");
                Timer timer = new Timer(1500, e -> {
                    new MenuPrincipalView(this.usuarioLogado).setVisible(true);
                    this.dispose();
                });
                timer.setRepeats(false);
                timer.start();

            } else {
                // Caso a votação principal não tenha sido salva
                exibirMensagem("Falha ao salvar os dados principais da votação.");
            }

        } catch (Exception e) {
            exibirMensagem("Erro ao finalizar a votação: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed

        CriarVotacaoView telaCriarVotacao = new CriarVotacaoView(this.usuarioLogado, votacaoEmAndamento);

        telaCriarVotacao.setLocationRelativeTo(null);
        telaCriarVotacao.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAdicionarOpcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarOpcaoActionPerformed

        if (opcoesVisiveis < todosOsLabelsDeOpcao.size()) {
            // Pega o próximo label e campo da lista e os torna visíveis
            todosOsLabelsDeOpcao.get(opcoesVisiveis).setVisible(true);
            todosOsCamposDeOpcao.get(opcoesVisiveis).setVisible(true);

            opcoesVisiveis++; // Incrementa o contador para a próxima vez
        } else {
            // Opcional: Avisa que chegou no limite
            exibirMensagem("Limite máximo de opções atingido.");
            btnAdicionarOpcao.setEnabled(false); // Desabilita o botão
        }
    }//GEN-LAST:event_btnAdicionarOpcaoActionPerformed

    private void txtPerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerguntaActionPerformed

    private void txtOpcao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOpcao7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOpcao7ActionPerformed

    private void txtOpcao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOpcao3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOpcao3ActionPerformed

    private void txtOpcao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOpcao6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOpcao6ActionPerformed
private void inicializarMenuLateral() {
    
     java.util.List<javax.swing.JButton> botoes = java.util.Arrays.asList(
        criarVotacao, participarVotacao, gerenciaVotacao, aprovarVotacao, votoArquivado
    );
    
    configurarBotao(criarVotacao, "criarVoto.png");
    configurarBotao(participarVotacao, "peoplemais.png");
    configurarBotao(gerenciaVotacao, "configpast.png");
    configurarBotao(aprovarVotacao, "list_check.png");
    configurarBotao(votoArquivado, "arquivada.png");

    
    for (javax.swing.JButton botao : botoes) {
        adicionarListeners(botao);
    }
  
}


private void configurarBotao(javax.swing.JButton botao, String nomeIcone) {
   
   botao.putClientProperty("JButton.buttonType", "toolBarButton");
    
    
    botao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    botao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    
    
    botao.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 15));
    botao.setIconTextGap(15);

    
    botao.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

    
    try {
        botao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/" + nomeIcone)));
    } catch (Exception e) {
        System.out.println("ERRO ao carregar ícone: " + nomeIcone);
    }
}



private void adicionarListeners(javax.swing.JButton botao) {
   
    final java.awt.Color COR_FUNDO_SIDEBAR = painelSidebar.getBackground(); // A cor de fundo da sidebar (branco)
    final java.awt.Color COR_HOVER_AZUL = new java.awt.Color(235, 240, 255); // O azul bem clarinho do Figma

    
    botao.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            
            botao.setBackground(COR_HOVER_AZUL);
            botao.setOpaque(true); 
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            
            botao.setOpaque(false);
           
            botao.setBackground(COR_FUNDO_SIDEBAR); 
        }
    });

    
    botao.addActionListener(e -> {
        System.out.println("Botão '" + botao.getText() + "' clicado!");

    });
}
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelConteudo;
    private javax.swing.JLabel TituloO1;
    private javax.swing.JLabel TituloO2;
    private javax.swing.JLabel TituloO3;
    private javax.swing.JLabel TituloO4;
    private javax.swing.JLabel TituloO5;
    private javax.swing.JLabel TituloO6;
    private javax.swing.JLabel TituloO7;
    private javax.swing.JLabel TituloO8;
    private javax.swing.JLabel TituloP;
    private javax.swing.JLabel TituloPrincipal;
    private javax.swing.JButton aprovarVotacao;
    private javax.swing.JButton btnAdicionarOpcao;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton criarVotacao;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton gerenciaVotacao;
    private javax.swing.JLabel labelIconeMenu;
    private javax.swing.JLabel labelIconePerfil;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelNomeUsuario;
    private javax.swing.JLabel menutxt;
    private javax.swing.JPanel painelHeader;
    private javax.swing.JPanel painelHeaderDireita;
    private javax.swing.JPanel painelHeaderEsquerda;
    private javax.swing.JPanel painelSidebar;
    private javax.swing.JButton participarVotacao;
    private javax.swing.JTextField txtOpcao1;
    private javax.swing.JTextField txtOpcao2;
    private javax.swing.JTextField txtOpcao3;
    private javax.swing.JTextField txtOpcao4;
    private javax.swing.JTextField txtOpcao5;
    private javax.swing.JTextField txtOpcao6;
    private javax.swing.JTextField txtOpcao7;
    private javax.swing.JTextField txtOpcao8;
    private javax.swing.JTextField txtPergunta;
    private javax.swing.JButton votoArquivado;
    // End of variables declaration//GEN-END:variables
}