/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifro.calama.votacaofeedback.view;

import br.edu.ifro.calama.votacaofeedback.controller.VotacaoController;
import br.edu.ifro.calama.votacaofeedback.model.Grupo;
import br.edu.ifro.calama.votacaofeedback.model.Usuario;
import br.edu.ifro.calama.votacaofeedback.model.Votacao;
import br.edu.ifro.calama.votacaofeedback.repository.GrupoRepository;
import br.edu.ifro.calama.votacaofeedback.util.GrupoComboBoxRendererUtil;
import br.edu.ifro.calama.votacaofeedback.util.ToastUtil;
import br.edu.ifro.calama.votacaofeedback.view.CriarVotacaoOpcoesView;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author floriano
 */
public class CriarVotacaoView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CriarVotacaoView.class.getName());
    private Usuario usuarioLogado;
    private Votacao votacaoEmAndamento;

    
    public CriarVotacaoView(Usuario usuario, Votacao votacao) {
        initComponents();
        this.usuarioLogado = usuario;
        this.votacaoEmAndamento = votacao;
        
        
        if (this.usuarioLogado != null) {
           
            labelNomeUsuario.setText(this.usuarioLogado.getNome());
        }
        
    inicializarMenuLateral();
    javax.swing.SwingUtilities.invokeLater(() -> {
        carregarGrupos();
    });
    }
    
   private void carregarGrupos() {
    try {
        // 1. Cria uma lista vazia para montar todas as opções
        List<Grupo> gruposParaExibir = new ArrayList<>();

        // 3. Busca e adiciona os grupos reais do banco (cursos, etc.)
        GrupoRepository grupoRepository = new GrupoRepository();
        gruposParaExibir.addAll(grupoRepository.buscarTodos());
        
        comboParticipantes.setModel(new javax.swing.DefaultComboBoxModel(gruposParaExibir.toArray()));
        comboParticipantes.setRenderer(new GrupoComboBoxRendererUtil("Selecionar Participantes"));
        comboParticipantes.setSelectedIndex(-1);
        
    } catch (Exception e) {
        exibirMensagem("Erro ao carregar grupos: " + e.getMessage());
        e.printStackTrace();
    }
}
    
    public javax.swing.JTextField getTxtTitulo() {
        return txtTitulo;
    }
    public javax.swing.JTextArea getTxtDescricao() {
        return txtDescricao;
    }
    public javax.swing.JFormattedTextField getTxtDataInicial() {
        return txtDataInicial;
    }
    public javax.swing.JFormattedTextField getTxtDataFinal() {
        return txtDataFinal;
    }
    public javax.swing.JFormattedTextField getTxtDataDivulgacao() {
        return txtDataDivulgacao;
    }
    public javax.swing.JComboBox getComboParticipantes() {
        return comboParticipantes;
    }

    public void exibirMensagem(String mensagem) {

        ToastUtil toast = new ToastUtil(this, mensagem, ToastUtil.ToastType.ERROR, ToastUtil.ToastPosition.TOP_CENTER);
        toast.display();
    }
    
    public void exibirMensagemDeSucesso(String mensagem) {
    
    ToastUtil toast = new ToastUtil(
        this, mensagem, ToastUtil.ToastType.SUCCESS, ToastUtil.ToastPosition.BOTTOM_RIGHT
    );
    toast.display();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelHeader = new javax.swing.JPanel();
        painelHeaderEsquerda = new javax.swing.JPanel();
        labelIconeMenu = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();
        painelHeaderDireita = new javax.swing.JPanel();
        labelNomeUsuario = new javax.swing.JLabel();
        labelIconePerfil = new javax.swing.JLabel();
        painelSidebar = new javax.swing.JPanel();
        menutxt = new javax.swing.JLabel();
        criarVotacao = new javax.swing.JButton();
        participarVotacao = new javax.swing.JButton();
        gerenciaVotacao = new javax.swing.JButton();
        aprovarVotacao = new javax.swing.JButton();
        votoArquivado = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        painelConteudo = new javax.swing.JPanel();
        TituloPrincipal = new javax.swing.JLabel();
        TituloVotacao = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        TituloDesc = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextArea();
        TituloDateI = new javax.swing.JLabel();
        txtDataInicial = new javax.swing.JFormattedTextField();
        TituloDateF = new javax.swing.JLabel();
        txtDataFinal = new javax.swing.JFormattedTextField();
        TituloParticipante = new javax.swing.JLabel();
        comboParticipantes = new javax.swing.JComboBox<>();
        tituloDivulga = new javax.swing.JLabel();
        txtDataDivulgacao = new javax.swing.JFormattedTextField();
        btnCancelar = new javax.swing.JButton();
        btnAvancar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelHeader.setBackground(new java.awt.Color(0, 0, 51));
        painelHeader.setPreferredSize(new java.awt.Dimension(100, 50));
        painelHeader.setLayout(new java.awt.BorderLayout());

        painelHeaderEsquerda.setOpaque(false);
        painelHeaderEsquerda.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 5));

        labelIconeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu.png"))); // NOI18N
        labelIconeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelIconeMenuMouseClicked(evt);
            }
        });
        painelHeaderEsquerda.add(labelIconeMenu);

        labelLogo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelLogo.setForeground(new java.awt.Color(255, 255, 255));
        labelLogo.setText("OCTACORE");
        labelLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLogoMouseClicked(evt);
            }
        });
        painelHeaderEsquerda.add(labelLogo);

        painelHeader.add(painelHeaderEsquerda, java.awt.BorderLayout.LINE_START);

        painelHeaderDireita.setOpaque(false);
        painelHeaderDireita.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5));

        labelNomeUsuario.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        labelNomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelNomeUsuario.setText("Nome Usuario");
        painelHeaderDireita.add(labelNomeUsuario);

        labelIconePerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        painelHeaderDireita.add(labelIconePerfil);

        painelHeader.add(painelHeaderDireita, java.awt.BorderLayout.LINE_END);

        getContentPane().add(painelHeader, java.awt.BorderLayout.PAGE_START);

        painelSidebar.setBackground(new java.awt.Color(255, 255, 255));
        painelSidebar.setPreferredSize(new java.awt.Dimension(230, 0));
        painelSidebar.setLayout(new javax.swing.BoxLayout(painelSidebar, javax.swing.BoxLayout.Y_AXIS));
        painelSidebar.add(menutxt);

        criarVotacao.setText("Criar Votação");
        criarVotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarVotacaoActionPerformed(evt);
            }
        });
        painelSidebar.add(criarVotacao);

        participarVotacao.setText("Participar de Votação ");
        participarVotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participarVotacaoActionPerformed(evt);
            }
        });
        painelSidebar.add(participarVotacao);

        gerenciaVotacao.setText("Gerenciar Votação");
        gerenciaVotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciaVotacaoActionPerformed(evt);
            }
        });
        painelSidebar.add(gerenciaVotacao);

        aprovarVotacao.setText("Aprovar Votações\n");
        aprovarVotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aprovarVotacaoActionPerformed(evt);
            }
        });
        painelSidebar.add(aprovarVotacao);

        votoArquivado.setText("Votações Arquivadas");
        painelSidebar.add(votoArquivado);
        painelSidebar.add(filler1);

        getContentPane().add(painelSidebar, java.awt.BorderLayout.LINE_START);

        TituloPrincipal.setText("CRIAR VOTAÇÃO");

        TituloVotacao.setText("Título da Votação");

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        TituloDesc.setText("Descrição da Votação");

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);

        TituloDateI.setText("Data Inicial da Votação");

        try {
            txtDataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataInicialActionPerformed(evt);
            }
        });

        TituloDateF.setText("Data Final da Votação");

        try {
            txtDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        TituloParticipante.setText("Participantes");

        comboParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboParticipantesActionPerformed(evt);
            }
        });

        tituloDivulga.setText("Data De Divulgação dos Resultados");

        try {
            txtDataDivulgacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnCancelar.setText("X Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAvancar.setText("Avançar");
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelConteudoLayout = new javax.swing.GroupLayout(painelConteudo);
        painelConteudo.setLayout(painelConteudoLayout);
        painelConteudoLayout.setHorizontalGroup(
            painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConteudoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TituloPrincipal)
                .addGap(87, 87, 87))
            .addGroup(painelConteudoLayout.createSequentialGroup()
                .addGroup(painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConteudoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloVotacao)
                            .addGroup(painelConteudoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TituloDesc)
                                    .addComponent(TituloDateI)
                                    .addComponent(TituloDateF)
                                    .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelConteudoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TituloParticipante)
                            .addComponent(tituloDivulga)))
                    .addGroup(painelConteudoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCancelar)
                        .addGap(45, 45, 45)
                        .addComponent(btnAvancar))
                    .addGroup(painelConteudoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtDataDivulgacao, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1006, Short.MAX_VALUE))
        );
        painelConteudoLayout.setVerticalGroup(
            painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloPrincipal)
                .addGap(18, 18, 18)
                .addComponent(TituloVotacao, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TituloDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TituloDateI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TituloDateF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TituloParticipante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloDivulga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDataDivulgacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAvancar))
                .addContainerGap(288, Short.MAX_VALUE))
        );

        getContentPane().add(painelConteudo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelIconeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIconeMenuMouseClicked
        
        new Thread(new Runnable() {
            @Override
            public void run() {
                // Lógica robusta: se a largura for maior que 0, ele fecha. Senão, abre.
                if (painelSidebar.getWidth() > 0) {
                    try {
                        // Animação para fechar, começando da largura atual
                        for (int i = painelSidebar.getWidth(); i >= 0; i--) {
                            painelSidebar.setSize(i, painelSidebar.getHeight());
                            Thread.sleep(1);
                        }
                    } catch (InterruptedException ex) {
                        System.out.println(ex);
                    }
                } else {
                    try {
                        // Animação para abrir, de 0 até a largura desejada (210)
                        for (int i = 0; i <= 210; i++) {
                            painelSidebar.setSize(i, painelSidebar.getHeight());
                            Thread.sleep(1);
                        }
                    } catch (InterruptedException ex) {
                        System.out.println(ex);
                    }
                }
            }
        }).start();
    }//GEN-LAST:event_labelIconeMenuMouseClicked

    private void labelLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLogoMouseClicked
        MenuPrincipalView telaDeCriacao = new MenuPrincipalView(this.usuarioLogado);

        telaDeCriacao.setLocationRelativeTo(null);
        telaDeCriacao.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_labelLogoMouseClicked

    private void criarVotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarVotacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criarVotacaoActionPerformed

    private void participarVotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participarVotacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_participarVotacaoActionPerformed

    private void gerenciaVotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciaVotacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gerenciaVotacaoActionPerformed

    private void aprovarVotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aprovarVotacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aprovarVotacaoActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtDataInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataInicialActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
   
    try {
        // --- COLETANDO DADOS DA TELA 1 ---
        String titulo = getTxtTitulo().getText();
        String descricao = getTxtDescricao().getText();
        String dataInicialStr = getTxtDataInicial().getText();
        String dataFinalStr = getTxtDataFinal().getText();
        String dataDivulgacaoStr = getTxtDataDivulgacao().getText();
        Object itemSelecionado = getComboParticipantes().getSelectedItem();
        

        // Validação para garantir que um grupo válido foi selecionado
        if (itemSelecionado == null || ((Grupo) itemSelecionado).getIdGrupo() == 0) {
            exibirMensagem("Por favor, selecione um grupo de participantes válido.");
            return;
        }

        // Pega o objeto Grupo inteiro e depois o seu ID
        Grupo grupoSelecionado = (Grupo) itemSelecionado;
        int idGrupoSelecionado = grupoSelecionado.getIdGrupo();
        // --- FIM DA PARTE CRÍTICA ---
        
        // Validação simples
        if (titulo.trim().isEmpty() || dataInicialStr.trim().length() < 10) {
            exibirMensagem("Título e datas são obrigatórios para avançar.");
            return;
        }

        // Converte as datas
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        Date dataInicio = formatador.parse(dataInicialStr);
        Date dataFim = formatador.parse(dataFinalStr);
        Date dataDivulgacao = formatador.parse(dataDivulgacaoStr);
        
        javax.swing.JOptionPane.showMessageDialog(this, "ID do Grupo Selecionado: " + idGrupoSelecionado);
        
        // --- EMPACOTANDO OS DADOS EM UM OBJETO VOTACAO ---
        Votacao votacaoEmAndamento = new Votacao();
        votacaoEmAndamento.setTitulo(titulo);
        votacaoEmAndamento.setDescricao(descricao);
        votacaoEmAndamento.setDataInicio(dataInicio);
        votacaoEmAndamento.setDataFim(dataFim);
        votacaoEmAndamento.setDataResultado(dataDivulgacao);
        votacaoEmAndamento.setIdGrupoDestino(idGrupoSelecionado);
        votacaoEmAndamento.setIdCriador(this.usuarioLogado.getId());
        votacaoEmAndamento.setStatus("PENDENTE"); // Um status temporário

        // --- NAVEGANDO PARA A PRÓXIMA TELA E LEVANDO OS DADOS ---
        // Estamos passando tanto o usuário logado quanto a votação que estamos criando
        CriarVotacaoOpcoesView telaDeCriacao = new CriarVotacaoOpcoesView(this.usuarioLogado, votacaoEmAndamento);

        telaDeCriacao.setLocationRelativeTo(null);
        telaDeCriacao.setVisible(true);

    // 3. Fecha a janela atual do menu principal de forma limpa.
        this.dispose();

    } catch (Exception e) {
        exibirMensagem("Erro nos dados: " + e.getMessage());
        e.printStackTrace();
    }
// TODO add your handling code here:
    }//GEN-LAST:event_btnAvancarActionPerformed

    private void comboParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboParticipantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboParticipantesActionPerformed
    private void inicializarMenuLateral() {
    // Coloca todos os botões em uma lista para fácil acesso
     java.util.List<javax.swing.JButton> botoes = java.util.Arrays.asList(
        criarVotacao, participarVotacao, gerenciaVotacao, aprovarVotacao, votoArquivado
    );
    // 1. Aplica o estilo visual INICIAL a cada botão
    configurarBotao(criarVotacao, "criarVoto.png");
    configurarBotao(participarVotacao, "peoplemais.png");
    configurarBotao(gerenciaVotacao, "configpast.png");
    configurarBotao(aprovarVotacao, "list_check.png");
    configurarBotao(votoArquivado, "arquivada.png");

    // 2. Adiciona os eventos de mouse e clique a todos os botões
    for (javax.swing.JButton botao : botoes) {
        adicionarListeners(botao);
    }

   
}
    



private void configurarBotao(javax.swing.JButton botao, String nomeIcone) {
    
   botao.putClientProperty("JButton.buttonType", "toolBarButton");
    
    
    botao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    botao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    
    
    botao.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 15));
    botao.setIconTextGap(15);

    
    botao.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

   
    try {
        botao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/" + nomeIcone)));
    } catch (Exception e) {
        System.out.println("ERRO ao carregar ícone: " + nomeIcone);
    }
}



private void adicionarListeners(javax.swing.JButton botao) {
   
    final java.awt.Color COR_FUNDO_SIDEBAR = painelSidebar.getBackground(); 
    final java.awt.Color COR_HOVER_AZUL = new java.awt.Color(235, 240, 255); 

    
    botao.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
           
            botao.setBackground(COR_HOVER_AZUL);
            botao.setOpaque(true); 
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            // Quando o mouse sai, o fundo volta a ser transparente
            botao.setOpaque(false);
            // A linha abaixo é opcional, mas garante a cor certa
            botao.setBackground(COR_FUNDO_SIDEBAR); 
        }
    });

    // Adiciona a AÇÃO DE CLIQUE (que agora não faz nenhuma mudança visual)
    botao.addActionListener(e -> {
        System.out.println("Botão '" + botao.getText() + "' clicado!");
        // Futuramente, aqui entrará a lógica do CardLayout para trocar a tela
    });
}
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloDateF;
    private javax.swing.JLabel TituloDateI;
    private javax.swing.JLabel TituloDesc;
    private javax.swing.JLabel TituloParticipante;
    private javax.swing.JLabel TituloPrincipal;
    private javax.swing.JLabel TituloVotacao;
    private javax.swing.JButton aprovarVotacao;
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<Grupo> comboParticipantes;
    private javax.swing.JButton criarVotacao;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton gerenciaVotacao;
    private javax.swing.JLabel labelIconeMenu;
    private javax.swing.JLabel labelIconePerfil;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelNomeUsuario;
    private javax.swing.JLabel menutxt;
    private javax.swing.JPanel painelConteudo;
    private javax.swing.JPanel painelHeader;
    private javax.swing.JPanel painelHeaderDireita;
    private javax.swing.JPanel painelHeaderEsquerda;
    private javax.swing.JPanel painelSidebar;
    private javax.swing.JButton participarVotacao;
    private javax.swing.JLabel tituloDivulga;
    private javax.swing.JFormattedTextField txtDataDivulgacao;
    private javax.swing.JFormattedTextField txtDataFinal;
    private javax.swing.JFormattedTextField txtDataInicial;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JButton votoArquivado;
    // End of variables declaration//GEN-END:variables

}
