/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.ifro.calama.votacaofeedback.view;

/**
 *
 * @author floriano
 */
public class TelaDeVotoView extends javax.swing.JPanel {

    /**
     * Creates new form TelaDeVotoView
     */
    public TelaDeVotoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        painelTitulo = new javax.swing.JPanel();
        lblTituloDaPagina = new javax.swing.JLabel();
        painelDetalhesVotacao = new javax.swing.JPanel();
        painelConteudoImagem = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        painelConteudoCentral = new javax.swing.JPanel();
        lblTituloEspecifico = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtAreaDescricaoVotacao = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        lblPergunta = new javax.swing.JLabel();
        painelDeOpcoes = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        painelTitulo.setBackground(new java.awt.Color(0, 0, 51));
        painelTitulo.setPreferredSize(new java.awt.Dimension(100, 60));
        painelTitulo.setLayout(new java.awt.BorderLayout());

        lblTituloDaPagina.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        lblTituloDaPagina.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloDaPagina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloDaPagina.setText("VOTAÇÃO");
        painelTitulo.add(lblTituloDaPagina, java.awt.BorderLayout.CENTER);

        add(painelTitulo, java.awt.BorderLayout.PAGE_START);

        painelDetalhesVotacao.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/IF.png"))); // NOI18N

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        jLabel11.setText("jLabel11");

        javax.swing.GroupLayout painelConteudoImagemLayout = new javax.swing.GroupLayout(painelConteudoImagem);
        painelConteudoImagem.setLayout(painelConteudoImagemLayout);
        painelConteudoImagemLayout.setHorizontalGroup(
            painelConteudoImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConteudoImagemLayout.createSequentialGroup()
                .addGroup(painelConteudoImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConteudoImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(painelConteudoImagemLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3))
                        .addGroup(painelConteudoImagemLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5))
                        .addGroup(painelConteudoImagemLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel7))
                        .addGroup(painelConteudoImagemLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9)))
                    .addGroup(painelConteudoImagemLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        painelConteudoImagemLayout.setVerticalGroup(
            painelConteudoImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConteudoImagemLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(painelConteudoImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelConteudoImagemLayout.createSequentialGroup()
                        .addGroup(painelConteudoImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelConteudoImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelConteudoImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelConteudoImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelConteudoImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        painelDetalhesVotacao.add(painelConteudoImagem, java.awt.BorderLayout.LINE_END);

        painelConteudoCentral.setLayout(new javax.swing.BoxLayout(painelConteudoCentral, javax.swing.BoxLayout.Y_AXIS));

        lblTituloEspecifico.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblTituloEspecifico.setText("VOTAÇÃO PARA DIREÇÃO-GERAL DO CAMPUS CALAMA");
        painelConteudoCentral.add(lblTituloEspecifico);

        txtAreaDescricaoVotacao.setEditable(false);
        txtAreaDescricaoVotacao.setColumns(20);
        txtAreaDescricaoVotacao.setLineWrap(true);
        txtAreaDescricaoVotacao.setRows(5);
        txtAreaDescricaoVotacao.setText(",sa,m asxc ksa cah hd ahj akj hs  shj hjs n bjcjbcds ajadhj hja ajd hbchjd dhj dhj hdfhj dfhfhdfhfdhj cfjh cjhf hjcf fj bj fjh cjc j dfchj fdjh jhfd cfhj cfhj fdchja cha jha hj hjds dhj hj");
        txtAreaDescricaoVotacao.setWrapStyleWord(true);
        txtAreaDescricaoVotacao.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAreaDescricaoVotacao, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(392, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAreaDescricaoVotacao, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelConteudoCentral.add(jPanel1);

        lblPergunta.setText("teste teste?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblPergunta)
                .addContainerGap(547, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPergunta)
                .addGap(23, 23, 23))
        );

        painelConteudoCentral.add(jPanel2);

        painelDetalhesVotacao.add(painelConteudoCentral, java.awt.BorderLayout.CENTER);

        add(painelDetalhesVotacao, java.awt.BorderLayout.CENTER);

        painelDeOpcoes.setLayout(new javax.swing.BoxLayout(painelDeOpcoes, javax.swing.BoxLayout.Y_AXIS));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("jRadioButton2");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        painelDeOpcoes.add(jRadioButton2);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("teste");
        painelDeOpcoes.add(jRadioButton1);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("jRadioButton3");
        painelDeOpcoes.add(jRadioButton3);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("jRadioButton4");
        painelDeOpcoes.add(jRadioButton4);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("jRadioButton5");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        painelDeOpcoes.add(jRadioButton5);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setText("x");
        jPanel3.add(jButton1);

        jButton2.setText("jButton2");
        jPanel3.add(jButton2);

        painelDeOpcoes.add(jPanel3);

        add(painelDeOpcoes, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JLabel lblPergunta;
    private javax.swing.JLabel lblTituloDaPagina;
    private javax.swing.JLabel lblTituloEspecifico;
    private javax.swing.JPanel painelConteudoCentral;
    private javax.swing.JPanel painelConteudoImagem;
    private javax.swing.JPanel painelDeOpcoes;
    private javax.swing.JPanel painelDetalhesVotacao;
    private javax.swing.JPanel painelTitulo;
    private javax.swing.JTextArea txtAreaDescricaoVotacao;
    // End of variables declaration//GEN-END:variables
}
