/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.ifro.calama.votacaofeedback.view;

import br.edu.ifro.calama.votacaofeedback.model.Usuario;
import br.edu.ifro.calama.votacaofeedback.model.Votacao;
import br.edu.ifro.calama.votacaofeedback.service.VotacaoService;
import java.util.List;

/**
 *
 * @author floriano
 */
public class VotacoesAtivasView extends javax.swing.JPanel {

    /**
     * Creates new form VotacoesAtivasView
     */
    public VotacoesAtivasView() {
        initComponents();
       
    }
    public void carregarVotacoes(Usuario usuarioLogado) {
    // Cria uma instância do nosso serviço
    VotacaoService votacaoService = new VotacaoService();

    try {
        // CHAMA O NOVO MÉTODO para buscar os dados filtrados
        List<Votacao> votacoesAtivas = votacaoService.buscarAtivasPorUsuario(usuarioLogado);

        // Limpa a grade antes de adicionar novos cards
        this.removeAll();

        // Para cada votação que veio do banco, cria e adiciona um card
        for (Votacao votacao : votacoesAtivas) {
            CardView card = new CardView();
            card.setDados(votacao); 
            this.add(card);
        }

        // Atualiza a interface para mostrar as mudanças
        this.revalidate();
        this.repaint();

    } catch (Exception e) {
        e.printStackTrace();
        // Mostra uma mensagem de erro para o usuário
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(0, 3, 15, 15));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
