/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.ifro.calama.votacaofeedback.view;

import br.edu.ifro.calama.votacaofeedback.model.Usuario;
import br.edu.ifro.calama.votacaofeedback.model.Votacao;
import br.edu.ifro.calama.votacaofeedback.service.VotacaoService;
import java.util.List;

/**
 *
 * @author floriano
 */
public class VotacoesAtivasView extends javax.swing.JPanel {

    private final MenuPrincipalView menuPrincipal;
    private Usuario usuarioLogado;
    
    public VotacoesAtivasView(MenuPrincipalView menuPrincipal, Usuario usuario) {
        initComponents();
        this.menuPrincipal = menuPrincipal;
        this.usuarioLogado = usuario;
    }
    public void carregarVotacoes(Usuario usuarioLogado) {
   
    VotacaoService votacaoService = new VotacaoService();

    try {
       
        List<Votacao> votacoesAtivas = votacaoService.buscarVotacoesAtivasPorUsuario(usuarioLogado);

       
        this.removeAll();

       
        for (Votacao votacao : votacoesAtivas) {
            CardView card = new CardView();
            card.setDados(votacao);
            card.setModo(DetalhesVotacaoDialog.ModoDialogo.PARTICIPACAO);
            this.add(card);
}
        for (Votacao votacao : votacoesAtivas) {
    CardView card = new CardView();
    card.setDados(votacao);
    card.setUsuario(usuarioLogado);
    this.add(card);
}

        
        this.revalidate();
        this.repaint();

    } catch (Exception e) {
        e.printStackTrace();
        
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(0, 3, 15, 15));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
